appengine/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    (r"^$", "dominationgame.views.frontpage"),
    (r"^edit_groups/$", "dominationgame.views.edit_groups"),
    (r"^login/$", "dominationgame.views.login"),
    (r"^connect/$", "dominationgame.views.connect_account"),
    (r"^tasks/laddermatch/$", "dominationgame.views.laddermatch"),
    (r"^tasks/update_team_scores/$", "dominationgame.views.update_team_scores"),
    (r"^tasks/clean/$", "dominationgame.views.clean"),
    (r"^(?P<groupslug>[\w\-]+)/$", "dominationgame.views.group"),
    (r"^(?P<groupslug>[\w\-]+)/dashboard/$", "dominationgame.views.dashboard"),
    (r"^(?P<groupslug>[\w\-]+)/upload_blob/$", "dominationgame.views.upload_blob"),
    (r"^(?P<groupslug>[\w\-]+)/brain/(?P<brain_id>\d+)/$", "dominationgame.views.brain"),
    (r"^(?P<groupslug>[\w\-]+)/brain/(?P<brain_id>\d+)/download/$", "dominationgame.views.brain_download"),
    (r"^(?P<groupslug>[\w\-]+)/team/(?P<team_id>\d+)$", "dominationgame.views.team"),
    (r"^(?P<groupslug>[\w\-]+)/game/(?P<game_id>\d+)$", "dominationgame.views.game"),
    (r"^(?P<groupslug>[\w\-]+)/replay/(?P<game_id>\d+)$", "dominationgame.views.replay"),
    (r"^(?P<groupslug>[\w\-]+)/download_data/(?P<data_id>\d+)$", "dominationgame.views.download_data"),
    (r"^(?P<groupslug>[\w\-]+)/settings/$", "dominationgame.views.settings"),
    (r"^(?P<groupslug>[\w\-]+)/games/csv/$", "dominationgame.views.games_csv"),
    (r"^(?P<groupslug>[\w\-]+)/brains/csv/$", "dominationgame.views.brains_csv"),
)

appengine/dominationgame/models.py
### Imports ###

# Future imports
from __future__ import with_statement

# Python Imports
import os
import re
import hashlib
import logging
import pickle
import gzip
import base64 as b64
from datetime import datetime, date, time, timedelta

# AppEngine Imports
from google.appengine.ext import db
from google.appengine.ext import deferred
from google.appengine.ext import blobstore
from google.appengine.api import mail
from google.appengine.api import files
from google.appengine.api.app_identity import get_application_id, get_default_version_hostname

# Django Imports
from django.utils.safestring import mark_safe
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify

# Library Imports
from domination import core as domcore
from domination.scenarios import MatchInfo
import trueskill


### Constants ###
APP_URL = "http://aamasgame.appspot.com"
MAX_ACTIVE_BRAINS = 3
MAX_ERRORS = 10

### Exceptions ###

### Properties ###

class TimeDeltaProperty(db.Property):
    """ Timedelta in seconds, stored as integer """
    def get_value_for_datastore(self, model_instance):
        td = super(TimeDeltaProperty, self).get_value_for_datastore(model_instance)
        if td is not None:
            return (td.seconds + td.days * 86400)
        return None
    
    def make_value_from_datastore(self, value):
        if value is not None:
            return timedelta(seconds=value)


class SlugProperty(db.StringProperty):
    """A (rough) App Engine equivalent to Django's SlugField."""
    
    def __init__(self, auto_calculate, **kwargs):
        """Initialize a slug with the property to base it on.
        """
        super(SlugProperty, self).__init__(**kwargs)
        self.auto_calculate = auto_calculate

    def get_value_for_datastore(self, model_instance):
        """Convert slug into format to go into the datastore."""
        value = self.auto_calculate.__get__(model_instance, None)
        return unicode(slugify(value))

    def validate(self, value):
        """Validate the slug meets formatting restrictions."""
        # Django does [^\w\s-] to '', strips, lowers, then [-\s] to '-'.
        if value and (value.lower() != value or ' ' in value):
            raise db.BadValueError("%r must be lowercase and have no spaces" % value)
        return super(SlugProperty, self).validate(value)

### Models ###

class Group(db.Model):
    name   = db.StringProperty(required=True)
    slug   = SlugProperty(name)
    added  = db.DateTimeProperty(auto_now_add=True)
    active = db.BooleanProperty(default=True)
    # Group settings
    gamesettings  = db.TextProperty(default="{}")
    field         = db.TextProperty(default="")
    release_delay = TimeDeltaProperty(default=timedelta(days=5))
    max_uploads   = db.IntegerProperty(default=10)
    
    def __str__(self):
        return self.name
    
    def url(self):
        if self.slug is None:
            self.slug = slugify(self.name)
        return reverse("dominationgame.views.group", args=[self.slug])
        
    def ladder_brains(self):
        q = self.brain_set.filter('active',True)
        return sorted(q, key=lambda b: b.conservative, reverse=True)
        
    def ladder_teams(self):
        return sorted(self.team_set, key=lambda x:x.maxscore, reverse=True)
        
    def recent_games(self):
        return self.game_set.order('-added').fetch(10)
        
    def gamesettings_obj(self):
        try:
            return domcore.Settings(**eval(self.gamesettings))
        except:
            return domcore.Settings()
            
    def field_obj(self):
        if self.field is None:
            return None
        try:
            return domcore.Field.from_string(self.field)
        except:
            return None
    
class Team(db.Model):
    group       = db.ReferenceProperty(Group, required=True)
    name        = db.StringProperty(required=True)
    number      = db.IntegerProperty(default=1)
    hashed_code = db.StringProperty(required=True)
    added       = db.DateTimeProperty(auto_now_add=True)
    emails      = db.StringListProperty()
    # Brains
    brain_ver = db.IntegerProperty(default=0)
    actives   = db.ListProperty(db.Key)
    maxscore  = db.FloatProperty(default=0.0)
    
    @classmethod
    def create(cls, group, **kwargs):
        kwargs['hashed_code'] = b64.urlsafe_b64encode(os.urandom(32))
        kwargs['number'] = group.team_set.count() + 1
        kwargs['parent'] = group
        return cls(group=group, **kwargs)
        
    @classmethod
    def get_by_secret_code(cls, secret_code):
        hashed_code = b64.urlsafe_b64encode(hashlib.sha224(secret_code).digest())
        return cls.all().filter('hashed_code =', hashed_code).get()
        
    def activate(self, brains):
        for brain in self.brain_set:
            brain.active = False
            brain.put()
        for i,brain in enumerate(brains):
            brain.active = True
        self.actives = [b.key() for b in brains]
        def txn():
            db.put(brains)
            self.put()
        db.run_in_transaction(txn)
    
    def send_invites(self, new_emails):
        self.emails = list(set(email.lower() for email in (self.emails + new_emails)))
        secret_code = b64.urlsafe_b64encode(os.urandom(32))
        self.hashed_code = b64.urlsafe_b64encode(hashlib.sha224(secret_code).digest())
        url = APP_URL + reverse("dominationgame.views.connect_account") + '?c=' + secret_code
        mailbody = """
                L.S.
                
                This is an invitation to join a team for the Domination game.
                You've been invited to join %s.
                Use the following link to confirm:
                
                %s
                
                Regards,
                
                Your TA
                """%(str(self), url)
        logging.info(mailbody)
        for email in new_emails:
            mail.send_mail(sender="noreply@%s.appspotmail.com"%get_application_id(),
                           to=email,
                           subject="Invitation to join a team for %s"%(self.group.name),
                           body=mailbody)
        self.put()
        
        
    def __str__(self):
        return "Team %d: %s"%(self.number, self.name)

    def url(self):
        return reverse("dominationgame.views.team", args=[self.group.slug, self.key().id()])
        
    def anchor(self):
        return mark_safe('<a href="%s">%s</a>' % (self.url(), str(self)))
        
    def recent_upload_count(self):
        """ How many brains were uploaded in the last 7 days. """
        recent = datetime.now() - timedelta(days=7)
        return self.brain_set.filter('added >', recent).count(10)
        
    def members(self):
        """ Returns a list of members """
        return Account.all().filter('teams', self.key())
        
    def activebrains(self):
        """ Returns dereferenced active brains """
        return Brain.get(self.actives)
        
    def activebrainkeyids(self):
        """ Returns key.id's for active brains """
        return [str(k.id()) for k in self.actives]
        
    def allbrains(self):
        """ Returns this team's brains, but ordered. """
        return self.brain_set.order('added')
        

class Account(db.Model):
    added = db.DateTimeProperty(auto_now_add=True)
    nickname = db.StringProperty()
    teams = db.ListProperty(db.Key)
    
    current_user = None
    current_team = None

    def short_name(self):
        return self.nickname[:20]


class BrainData(db.Model):
    """ Stores reference to binary data blob for an
        agent brain
    """
    blob     = blobstore.BlobReferenceProperty(required=True)
    filename = db.StringProperty()
    added    = db.DateTimeProperty(auto_now_add=True)
    team     = db.ReferenceProperty(Team, required=True)
    
    @classmethod
    def create(cls, team, datafile):
        file_name = files.blobstore.create(mime_type='application/octet-stream')
        with files.open(file_name, 'a') as f:
            for chunk in datafile.chunks():
                f.write(chunk)
        files.finalize(file_name)
        blob_key = files.blobstore.get_blob_key(file_name)
        braindata = cls(blob=blobstore.BlobInfo.get(blob_key),
                        team=team,
                        filename=datafile.name,
                        parent=team.group)
        braindata.put()
        
    def download_url(self):
        return reverse("dominationgame.views.download_data", args=[self.parent().slug, self.key().id()])
            
class Brain(db.Model):
    # Performance stats
    score        = db.FloatProperty(default=100.0)
    uncertainty  = db.FloatProperty(default=30.0)
    conservative = db.FloatProperty(default=0.0)
    active       = db.BooleanProperty(default=False)
    games_played = db.IntegerProperty(default=0)
    num_errors   = db.IntegerProperty(default=0)
    # Identity
    group   = db.ReferenceProperty(Group, required=True)
    team    = db.ReferenceProperty(Team, required=True)
    name    = db.StringProperty(default='unnamed')
    version = db.IntegerProperty(default=1)
    # Timestamps
    added       = db.DateTimeProperty(auto_now_add=True)
    last_played = db.DateTimeProperty()
    # Source code
    source       = db.TextProperty(required=True)
    data         = db.ReferenceProperty(BrainData)    
    
    def __str__(self):
        return mark_safe("%s v%d"%(self.name[:20], self.version))
        
    def identifier(self):
        return "t%dv%d"%(self.team.number, self.version)
    
    @classmethod
    def create(cls, team, source, **kwargs):
        kwargs['version'] = team.brain_ver + 1
        kwargs['group'] = team.group
        # Try to extract a name
        kwargs['name'] = domcore.Team(source).name_internal
        # Create entity and put
        brain = cls(team=team, source=source, parent=team.group, **kwargs)
        team.brain_ver += 1
        team.put()
        brain.put()

appengine/templates/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}Domination Game{%endblock%}</title>
    <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
    <link rel="stylesheet" href="/static/theme/codemirror.css" type="text/css" media="screen" title="no title" charset="utf-8">
    <link rel="stylesheet" href="/static/theme/style.css" type="text/css" media="screen" title="no title" charset="utf-8">
    
    <script src="/static/javascript/mootools-core-1.4.2-full.js" type="text/javascript" charset="utf-8"></script>
    <script src="/static/javascript/mootools-more-1.4.0.1.js" type="text/javascript" charset="utf-8"></script>
    <script src="/static/javascript/openid.js" type="text/javascript" charset="utf-8"></script>
    <script src="/static/javascript/codemirror.js" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		window.addEvent('domready', function(){
			//Activate pills
			$$('.tabs').each(function(ul){
				var all_pills = ul.getElements('li');
				var all_inside = $$(ul.getElements('li a').get('href').join(','));
				all_inside.setStyle('display','none')
				ul.getElements('li').each(function(li){
					li.addEvent('click', function(e){
						all_inside.setStyle('display','none');
						all_pills.removeClass('active');
						$$(this.getElement('a').get('href')).setStyle('display','block');
						this.addClass('active');
					}.bind(li));
				});
				$$(ul.getElement('li.active a').get('href')).setStyle('display','block');
			});
			
			$$('.alert-message .close').each(function(closebtn){
				closebtn.addEvent('click', function(e){
					this.getParent().destroy();
				})
			});
		})
	</script>
</head>

<body>
	<div class='topbar'>
		<div class='fill'>
		    <div class="container">
				<h3><a href='/'>{% block headertext %}{% endblock %}</a></h3>
				<ul class="nav secondary-nav">
				{% if user %}
					{% if group and user.is_admin %}<li><a href='{% url dominationgame.views.settings group.slug %}'>Admin Settings</a></li>{%endif%} 
					{% if user.current_team %} 
						<li><a href='{% url dominationgame.views.dashboard user.current_team.group.slug %}'>Dashboard</a></li>{% endif %}
					<li><a href='{{user.logout_url}}'>Logout ({{user.short_name}})</a></li>
				{% else %}
					<li><a href='/login'>Login</a></li>
				{% endif %}
				</ul>
			</div>
		</div>
	</div>
	<div class='container'>
		{% for message in messages %}
			<div class='alert-message {{message.0}}'><a class="close" href="#">×</a>{{message.1}}</div>
		{% endfor %}
    {% block content %}

    Dit is de base template.
    
    {% endblock content %}
    
    </div>

    <div id="footer">
    </div>

</body>

</html>

appengine/templates/base_group.html
{% extends "base.html" %}

{% block headertext %}
Domination Game <strong>{{group.name}}</strong>
{% endblock %}

appengine/templates/brain.html
{% extends "base_group.html" %}


{% block content %}

<h1>{{brain}} <small>by {{brain.team.anchor}}</small></h1>
<div class='row'>
	<div class='span6'>
        <h2>Info</h2>
		<table><tbody>
			<tr><td><strong>Uploaded on:</strong></td><td>{{brain.added}}</td></tr>
			<tr><td><strong>Score:</strong></td><td>{{brain.conservative|floatformat}} 
				<span class='light'>( {{brain.score|floatformat}} &plusmn; {{brain.uncertainty|floatformat}} )</span>
			</td></tr>
			<tr><td><strong>Games played:</strong></td><td>{{brain.games_played}}</td></tr>
			<tr><td><strong>Errors:</strong></td><td>{{brain.num_errors}}</td></tr>
		</tbody></table>
	</div>
    <div class='span10'>
        <h2>Games</h2>
        <table>
            <tbody>
                {% for game in brain.games %}
                <tr><td>{{game.game.added}}</td>
                    <td>{{game.my_score}} - {{game.opp_score}}</td>
                    <td>{{game.opponent.anchor}}</td>
                    <td><a href="{{game.game.url}}">view</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div id='source'>
	<h2>Source code &amp; Data</h2>
	{% if not brain.released %}
	<span class="label notice">release on {{brain.release_date}}</span>
	{% endif %}
	
	{% if brain.released or user.is_admin or brain.owned_by_current_user %}
    <p><strong>Blob:</strong> {% if brain.data %}
        <a href="{{brain.data.download_url}}?fn={{brain.identifier}}_blob">Download</a>
        {% else %}
        None
        {% endif %}
    </p>
	<pre id='code'>{{brain.source}}</pre>
    <!-- <pre id='output' class="cm-s-default"> -->
	</pre>
	<script type="text/javascript" charset="utf-8">
    var content = $('code').get('text');
    $('code').empty()
    var a = CodeMirror($('code'), {'value': content,
                           'name': 'python',
                           'lineNumbers': true,
                           'readOnly': true});
    // CodeMirror.runMode($("code").get('text'),  {name: "python", lineNumbers: 'true'}, $('output'));
    // $('code').destroy();
	</script>
	{% endif %}
</div>

{% endblock content %}

appengine/templates/connect.html
{% extends "base.html" %}

{% block content %}
<div class='hero-unit'>
	<h1>Welcome<br/> to the Domination Game!</h1>
	<p>By entering the secret code that was sent to you below, you will join a team in this competition</p>
	<form method="post" action="/connect/" class='form-stacked'>
	    <fieldset>
	    	<label for='code'>Team secret code: </label><input type="text" id='code' name='secret_code' style="width: 500px" value="{{secret_code}}"/>
			<input type="submit" class='btn primary' value="Connect to team." />
	    </fieldset>
	</form>
</div>

{% endblock %}

appengine/templates/dashboard.html
{% extends "base_group.html" %}

{% block content %}
<h1>{{user.current_team.name}} <small>Dashboard</small></h1>

<div class='row'>
	<div class='span10'>
		<p>Welcome to your dashboard. Here you and your teammembers can choose which of your uploaded brains are 
			active in the competition ladder. You can also upload new brains and binary data here.
		</p>
	</div>
	<div class='span6'>
	<h4>Members</h4>
	<ul class='unstyled'>
		{% for member in user.current_team.members %}
			<li>{{member.short_name}} ({{member.key.name}})</li>
		{% endfor %}
	</ul>
	</div>
</div>

<ul class='tabs'>
  <li class="active"><a href="#upload-agent">Upload agent</a></li>
  <li><a href="#select-active">Select active</a></li>
  <li><a href="#upload-blob">Upload blob</a></li>
</ul>	

<div>

	<div id='upload-agent'>
		<p>You have uploaded <strong>{{user.current_team.recent_upload_count}}/{{group.max_uploads}} brains</strong> in this 7 day period.
			Note that all code you upload here will be <strong>released after {{group.release_delay.days}} days</strong>. This means it will
			be avaible to other teams and any other visitors to this site. You can select which of your uploaded binary blobs will be supplied
            to this agent every game, this means you have to upload this blob first.
		</p>
		
		<form class='form-stacked flushleft' method="post" action="">	
			<fieldset>
			<legend>Upload new brain</legend>

            Use binary blob: <select name='blobid'>
                <option value='None'>None</option>
                {% for braindata in user.current_team.braindata_set %}
                    <option value='{{braindata.key.id}}'>{{braindata.filename}}-{{braindata.added}}</option>
                {% endfor %}
            </select>
            <hr/>
			<textarea id='newbrain' name='newbrain' rows='100' cols='80'># Paste your code.</textarea>
			<script type="text/javascript" charset="utf-8">
				var myCodeMirror = CodeMirror.fromTextArea(document.id('newbrain'), {'lineNumbers':true});
			</script>
			<div class='actions'><input type='submit' class='btn primary' value='Upload new brain'></input></div>
			</fieldset>
		</form>
	</div>
	
	<div id='select-active'>
		<p>Select your active brains. You can have throee brains active at the same time, these will be selected at
			random to play games against other agents. Note that <strong>Agent A</strong> is assumed to be your best agent,
			this is the agent that is downloaded in a snapshot.</p>
	<form method="post" action="" class='form-stacked flushleft'>
		<p>
		<input id='activebrains' type='hidden' name='activebrains' value='{{user.current_team.activebrainkeyids|join:","}}'>
		<fieldset>
		<legend>Select active brains</legend>
		<div id='active-agent-select' class='row'>
		{% for letter in "ABC"|make_list %}
			<div class='span-one-third'>
				<label>Brain {{letter}}</label>
					{% for brain in user.current_team.allbrains %}
					<input type='radio' id="brain-{{letter}}-{{brain.key.id}}" name="brain-{{letter}}" value='{{brain.key.id}}'>
					<span><a href="{{brain.url}}">{{brain}}</a></span>
					<br/>
					{% endfor %}
			</div>
		{% endfor %}
		</div>
	
		<div class='actions'><input type='submit' class='btn primary' value='Save'></input></div>
		</fieldset>
	</form>

	<script type="text/javascript" charset="utf-8">
	var ids = $('activebrains').value.split(',');
	for (var i = 0; i < ids.length; i++){
		var l = "ABC"[i];
		var htmlid = 'brain-'+l+'-'+ids[i];
		$(htmlid).set('checked', true);
	}
	</script>
	</div>

	
	<div id='upload-blob'>
		<p>Upload a binary blob here. A <em>reader</em> to this file will be passed to your agent in the <code>__init__</code>
			method, with an argument name <code>blob</code>. If you pickled an object into this file, use it with 
			<code>obj = pickle.reads(blob.read())</code>. Feel free to store any kind of data in here (pickled is a good choice), 
			but keep it under 4 MB. 
		</p>
		<form class='form-stacked flushleft' method="POST" action="{{upload_url}}" enctype="multipart/form-data">	
			<fieldset>
			<legend>Upload new binary blob</legend>
            <input type="file" name="file">
			<div class='actions'><input type='submit' name='submit' class='btn primary' value='Submit'></input></div>
			</fieldset>
		</form>
	</div>
	
</div>


{% endblock content %}

appengine/templates/front.html
{% extends "base.html" %}

{% block content %}

{{stats}}
    
{% endblock content %}

appengine/templates/game.html
{% extends "base_group.html" %}

{% block content %}


<div class='row'>
	<div class='span-one-third' style='text-align: right'>
		<h3>Red</h3>
		<a href='{{game.red.team.url}}'>{{game.red.team}}</a> <a href='{{game.red.url}}'>{{game.red}}</a><br/>
		<h3>{{game.score_red}}</h3>
		<span class='light'>{{game.red_score_diff|floatformat}}</span>
	</div>
	<div class='span-one-third'>
		<h3>Blue</h3>
		<a href='{{game.blue.team.url}}'>{{game.blue.team}}</a> <a href='{{game.blue.url}}'>{{game.blue}}</a>
		<h3>{{game.score_blue}}</h3>
		<span class='light'>{{game.blue_score_diff|floatformat}}</span>
	</div>	
	<div class='span-one-third'>
		<strong>Date:</strong> {{game.added}} <br/>
		
		<strong><a href='{{game.replay_url}}'>Download Replay</a></strong>
	</div>
</div>

<h3>Log</h3>
<pre>{{game.log}}</pre>


{% endblock content %}

appengine/templates/group.html
{% extends "base_group.html" %}

{% block content %}

<div class='row'>
	<div class="span6">
		<h2>Home</h2>
		<p>Welcome to {{group.name}}'s Domination Game home page. You can see an overview of the current rankings,
		and a list of recently played games. The team ranking is computed periodically, so it might be slighly 
		outdated.</p>
		<h3>Rankings</h3>
		<p>Rankings are based on matches played between randomly selected opponent brains. The teams' scores are
		updated using a 2-player variation on the <a href="http://research.microsoft.com/en-us/projects/trueskill/">TrueSkill ranking system</a>, which is itself an extension of the <a href="http://en.wikipedia.org/wiki/Elo_rating_system">Elo rating system</a>. What you see here are the &ldquo;conservative skill estimates&rdquo;, the current estimated skill mean minus the standard deviation. Teams are ranked based on their highest scoring active brain.</p>
	</div>
	<div class='span10'>
		<ul class="tabs">
		  <li class="active"><a href="#ranking-brains">Brains</a></li>
		  <li><a href="#ranking-teams">Teams</a></li>
		</ul>
		<div>
			<div id="ranking-brains">
				<table class='bordered-table zebra-striped'>
					<thead><tr><th>#</th><th>Score</th><th>Name</th></tr></thead>
					<tbody>
						{% for brain in group.ladder_brains %}
						<tr>
							<td>{{forloop.counter}}</td>
							<td>{{brain.conservative|floatformat:1}}</td>
							<td><strong>{{brain.team.anchor}}</strong> {{brain.anchor}}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<div id="ranking-teams">
				<table class='bordered-table zebra-striped'>
					<thead><tr><th>#</th><th>Score</th><th>Name</th></tr></thead>
					<tbody>
						{% for team in group.ladder_teams %}
						<tr>
							<td>{{forloop.counter}}</td>
							<td>{{team.maxscore|floatformat:1}}</td>
							<td><strong><a href="{{team.url}}">{{team}}</a></strong></td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<div class='row'>
	<div class='span8'>
		<h3>Recent games</h3>
		<table class='condensed-table games-played'>
			<col align='right'><col align='right'><col align='center'>
			<thead><tr>
				<th class='aright'>Score</th>
				<th class='aright'>Red</th>
				<th class='acenter'>&nbsp;</th>
				<th>Blue</th>
				<th>Score</th>
			</tr></thead>
			<tbody>
				{% for game in group.recent_games %}
				<tr>
					<td class='aright'>{{game.score_red}}</td>
					<td class='aright'>{% if game.error_red %}<span class='label warning'>err</span>{% endif %}
						{{game.red.anchor}}
					</td>
					<td class='acenter'><a href='{{game.url}}'>{{game.winner}}</a></td>
					<td>{{game.blue.anchor}}
						{% if game.error_blue %}<span class='label warning'>err</span>{% endif %}
					</td>
					<td>{{game.score_blue}}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	<div class='span8'>
		<h3>Settings &amp; stats</h3>
		<p>Running <span style='font-weight:bold'>Domination Game Version {{dgversion}} on Python {{pyversion}}</span> . 
            The settings for the current game are <code>{{group.gamesettings_obj}}</code>.
        </p>
        
        {% if group.field_obj %}
        <h4>Field</h4>
        <pre style='font-size:0.7em; line-height: 1.2em'>{{group.field.strip}}</pre>
        {% endif %}
    </div>
</div>
			

{% endblock content %}

appengine/templates/groups_edit.html
{% extends "base.html" %}

{% block content %}


{% for group in groups %}
	<a href='{{group.url}}'>{{group.name}} ({{group.slug}})</a></br>
{% endfor %}

<form method="post" action="">
    <fieldset>
    	<label for='grp'>New group name: </label><input id='grp' name='groupname' type="text" style="width: 500px" /><input type="submit" value="Create group." class='btn'/>
    </fieldset>
</form>

{% endblock content %}

appengine/templates/team.html
{% extends "base_group.html" %}

{% block content %}

<h1>{{team}}</h1>

<div class='row'>
	<div class='span12'>
		<table>
			<thead><tr><th>Active</th><th>Uploaded</th><th>Score</th><th>Name</th><th>Downloads</th></thead>
			<tbody>
			{% for brain in team.allbrains %}<tr {% if not brain.active %}class="light"{%endif%}>
            <td>{% if team.activebrains|length > 0 %}{%ifequal brain.key.id team.activebrains.0.key.id %}<strong>A</strong>{%endifequal%}{%endif%}
                {% if team.activebrains|length > 1 %}{%ifequal brain.key.id team.activebrains.1.key.id %}<strong>B</strong>{%endifequal%}{%endif%}
                {% if team.activebrains|length > 2 %}{%ifequal brain.key.id team.activebrains.2.key.id %}<strong>C</strong>{%endifequal%}{%endif%}</td>
            <td>{{brain.added}}</td>
			<td>{{brain.conservative|floatformat}}</td>
			<td>
                {{brain.anchor}}{% if brain.num_errors %}<span class='label warning'>err</span>{% endif %}
			</td>
            <td>
                {% if brain.owned_by_current_user or user and user.is_admin %}
                    (<a href="{{brain.download_url}}">Download</a> / 
                    {{brain.blob_anchor}})
                {% endif %}
                
			</tr>{% endfor %}
			</tbody>
		</table>
	<div>
</div>


{% endblock content %}